import pygame

pygame.init()

TILE_BLANK = "blank"
TILE_VOID = "void"
TILE_CHOSEN = "chosen"
TILE_DIFFICULT = "difficult"

UNIT_SLIME = "slime"

SOUND_WELP = "welp.mp3"

STATUS_POISON = "poisoned"

UI_DEFAULT = "default"
UI_BATTLE = "battle"
UI_BATTLE_WIDTH = 1200
UI_BATTLE_HEIGHT = 900

BUTTON_END_TURN = "end_turn"
BUTTON_ATTACK = "attack"
BUTTON_ATTACK_WIDTH = 400
BUTTON_ATTACK_HEIGHT = 100
BUTTON_ATTACK_CONFIRM = "attack_confirm"
BUTTON_ATTACK_CANCEL = "attack_cancel"
BUTTON_ATTACK_OPTION_WIDTH = 100
BUTTON_ATTACK_OPTION_HEIGHT = 50

SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 1200
TILE_SIZE = 100
UNIT_MOVE_DURATION = 3
FRAME_RATE = 60

HEALTH_GREEN = (84, 168, 66)
HEALTH_YELLOW = (200, 209, 36)
HEALTH_ORANGE = (186, 142, 47)
HEALTH_RED = (163, 45, 18)
HEALTH_BAR_RATIO = 30

FONT_BATTLE = pygame.font.Font('fonts/Raleway-Light.ttf', 24)

